# Site settings
title: BMS353 Bioinformatics for Biomedical Science
session: 2019-2020
email: m.milo@sheffield.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Bioinformatics course in R for Biomedical Science students.
baseurl: "/bioinformatics" # the subpath of your site, e.g. /blog/
url: "http://opendsi.cc" # the base hostname & protocol for your site
twitter_username: marta_milo
github_username:  martamilo
banner: banner_image.jpg
# Build settings
markdown: kramdown
disqus: opendsiccbioinformatics
comments: true

analytics:
  google:
    tracking_id: UA-62964644-1
