# Site settings
title: BMS353 Bioinformatics for Biomedical Scientists
email: m.milo@sheffield.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/bioinformatics" # the subpath of your site, e.g. /blog/
url: "http://opendsi.cc" # the base hostname & protocol for your site
twitter_username: marta_milo
github_username:  martamilo
banner: banner_image.jpg
# Build settings
markdown: kramdown
disqus: opendsicc
comments: true

analytics:
  google:
    tracking_id: UA-62964644-1
